### ISSUE TITLE
Public or Private?

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/GUI-Cards#47]
--------------------------------------------
--------------------------------------------
**CARD--------------------------------------**
**Card CLASS**
- [ ] ? arraySort(Card[] cards, int arraySize) : void
- [ ] ? getSortRanking(Card card) : int

--------------------------------------------
--------------------------------------------
**PHASE 1**
- [ ] static final int NUM_CARD_IMAGES = 57;    
- [ ] static Icon[] icon = new ImageIcon[NUM_CARD_IMAGES];  
- [ ] static void loadCardIcons()
- [ ] static String turnIntIntoCardValue(int j)
- [ ] static String turnIntIntoCardSuit(int i)

--------------------------------------------
--------------------------------------------
PHASE 2

**Phase2 CLASS--------------------------------------------**

// should below be public and final?
- [ ] static int NUM_CARDS_PER_HAND = 7;
- [ ] static int NUM_PLAYERS = 2;
- [ ] static JLabel[] computerLabels = new JLabel[NUM_CARDS_PER_HAND];
- [ ] static JLabel[] humanLabels = new JLabel[NUM_CARDS_PER_HAND];
- [ ] static JLabel[] playedCardLabels = new JLabel[NUM_PLAYERS];
- [ ] static JLabel[] playLabelText = new JLabel[NUM_PLAYERS];
--------------------------------------------

**CardTable CLASS  -----Extends JFrame ------(Part of Phase2.java)**

// should below be public and final?
- [ ] static int MAX_CARDS_PER_HAND = 56;
- [ ] static int MAX_PLAYERS = 2;

// should below variables all really be public from CardTable class? Not private?
- [ ] public JPanel pnlComputerHand, pnlHumanHand, pnlPlayArea;

--------------------------------------------
**----------------FROM GUICard CLASS-----(Part of Phase2.java)**

- [ ] static void loadCardIcons()    
- [ ] static public Icon getIcon(Card card)
- [ ] static public Icon getBackCardIcon()
- [ ] static String turnIntIntoCardValue(int j)
- [ ] static String turnIntIntoCardSuit(int i)

**Comment by mdoussias** [comment]
Not sure if we want to be adding last minute changes to make things public or private.... But I need a team direction on if we should alter anything before I can complete the UML diagram?

**Comment by Mcghee-Jake** [comment]
All of the variables in caps should probably be made final. On top or that, all variables and methods should be made private UNLESS it throws an error in the program. Basically what I would do to solve this is make each variable/method private, see eclipse gives an error (you shouldn't even need to run the program) and if it does make it public. Im away from my computer otherwise I would test them out myself.

**Comment by p12345vls** [comment]
I just tested them and updated the google document

**Comment by mdoussias** [comment]
I'm going to fix the PUBLIC/private issue now in PHASE 2.

**Comment by mdoussias** [comment]
Phase 3 is not listed above but it still needs fixe.

**Comment by p12345vls** [comment]
I did it I will put request now

**Comment by mdoussias** [comment]
All is done.
